Fix the bbox bug in `ViewFinder`
pysheds/pysheds pull request #251
Opened 2024-04-14 19:39 UTC by cheginit

This PR Fixes the issue with getting the bounds wrong when affine has no rotation or the resolution is negative. (mdbartos/pysheds#250)

2026-03-27 20:47 UTC, JonKing93 requested changes

2026-03-27 20:47 UTC, JonKing93 commented on pysheds/sview.py
> +        return (minx, miny, maxx, maxy)
I could be wrong, but I believe this only fixes the bug in the case of a positive rotational affine transform. We probably want a more general solution that also handles shear transforms with mixed positive/negative signs.

@cheginit , does the following code work to fix #250 ? If so, I think it could be a more general fix
```
    @property
    def bbox(self):

        # Get the X and Y counts
        shape = self.shape
        ncols = shape[-1]
        nrows = shape[-2]

        # Get the coordinates for each corner of the view, clockwise from top left
        x_indices = [0, ncols, ncols, 0]
        y_indices = [0, 0, nrows, nrows]
        x_coords, y_coords = View.affine_transform(self.affine, x_indices, y_indices)

        # Bbox is defined by the min and max coordinates
        xmin = min(x_coords)
        xmax = max(x_coords)
        ymin = min(y_coords)
        ymax = max(y_coords)
        return (xmin, ymin, xmax, ymax)
```

2026-03-28 14:30 UTC, cheginit commented on pysheds/sview.py
> +        return (minx, miny, maxx, maxy)
You're right. I just combined the two approaches.

2026-03-31 16:43 UTC, JonKing93 requested changes

2026-03-31 16:43 UTC, JonKing93 commented on pysheds/sview.py
> +        return (min(xs), min(ys), max(xs), max(ys))
I don't think we need the `if-else` block anymore, as the general solution (in `else`) should also handle the translation case (in `if`). Attaching a test file with an example: 

[test_bbox_methods.py](https://github.com/user-attachments/files/26384020/test_bbox_methods.py)

~~Adding a suggestion for a vectorized version of the general solution here~~
Edited to use non-vectorized version to avoid numba overkill

```suggestion
        affine = self.affine
        ncols = self.shape[-1]
        nrows = self.shape[-2]

        # Get the coordinates of each corner, clockwise from top left
        c0x, c0y = affine.c, affine.f
        c1x, c1y = affine * (0, nrows)
        c2x, c2y = affine * (ncols, nrows)
        c3x, c3y = affine * (ncols, 0)

        # Parse the bounding box
        xs = (c0x, c1x, c2x, c3x)
        ys = (c0y, c1y, c2y, c3y)
        return (min(xs), min(ys), max(xs), max(ys))
```

2026-03-31 16:43 UTC, JonKing93 commented on tests/test_grid.py
These are great! I ran them with the vectorized version of the general solution and they all passed

2026-03-31 16:46 UTC, JonKing93 commented on pysheds/sview.py
> +        return (min(xs), min(ys), max(xs), max(ys))
@cheginit - If you're okay with me modifying the PR, I can commit this suggestion and merge with main

2026-03-31 16:58 UTC, cheginit commented on pysheds/sview.py
> +        return (min(xs), min(ys), max(xs), max(ys))
The point of `if-else` is that, for that case the affine transform is not needed and affine can be used directly without the extra computations. The reason that I did not use `View.affine_transform` is that this is just a simple computation and using `numba` for running 4 simple mathematical operations is an overkill. I'm ok with your suggestions though.

2026-04-01 20:54 UTC, JonKing93 commented on pysheds/sview.py
> +        return (min(xs), min(ys), max(xs), max(ys))
Got it, that makes sense. I like the simplicity of the general solution, but that's a good point about `numba` being overkill. I'll update it to use the non-vectorized version

2026-04-01 21:25 UTC, JonKing93 approved these changes

2026-04-21 18:34 UTC, JonKing93 commented
Hey @cheginit , I just noticed this merge stalled. If you want to approve the changes I made to the PR, I think it should be able to merge then

2026-04-21 19:11 UTC, cheginit commented
@JonKing93 I cannot approve it myself, it seems. Someone else from @pysheds/developers need to approve it.

2026-04-21 19:52 UTC, Zeitsperre approved these changes
Approving on behalf of @cheginit :shipit:

2026-04-21 19:55 UTC, merged